### ISSUE TITLE
adjusting effect sizes

### ISSUE THREAD

**Issue by swvanderlaan** [DudbridgeLab/indexevent#3]
Hi,

I am trying to apply your method. 

Am I correct in assuming I should harmonise datasets before applying this method?

Best,

Sander

**Comment by fdudbridge** [comment]
Hi Sander sorry I have not seen your comment until today.  I am still learning my way around github.  Yes indeed you have to harmonise the datasets so that the effects refer to the same alleles.  This is something we could add into a future version so that it could take the original plink output (for example) and harmonise the alleles automatically.
best wishes, Frank
